// Enhanced PDF Generator with Multilingual Support
// Integrates with existing app to create beautiful fertilizer requirement reports

// Import jsPDF and AutoTable (ESM)
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

// Language translation data
const translations = {
  english: {
    title: 'Crop Fertilizer Recommendation Report',
    subtitle: 'Optimized Fertilizer Requirements',
    farmer: 'Farmer',
    date: 'Date',
    id: 'ID',
    soilInfo: 'Soil & Location Information',
    soilType: 'Soil Type',
    soilpH: 'Soil pH',
    nitrogen: 'Nitrogen',
    phosphorus: 'Phosphorus',
    potassium: 'Potassium',
    district: 'District',
    agroZone: 'Agro-ecological Zone',
    season: 'Season',
    landArea: 'Land Area',
    hectares: 'hectares',
    avgHumidity: 'Avg Humidity',
    avgRainfall: 'Avg Rainfall',
    temperature: 'Temperature',
    weather: 'Weather Conditions',
    windSpeed: 'Wind Speed',
    precipitation: 'Precipitation',
    cropRec: 'AI Crop Recommendation',
    bestMatch: 'Best Match',
    confidence: 'Confidence',
    modelAccuracy: 'Model Accuracy',
    altOptions: 'Alternative Options',
    fertilizerRec: 'Fertilizer Requirements',
    purpose: 'Purpose',
    rate: 'Rate per hectare',
    totalNeeded: 'Total needed for your land',
    soilConsider: 'Soil Considerations',
    managementTips: 'Management Tips',
    basal: 'basal',
    topDressed: 'top dressed',
    or: 'OR',
    mainNSource: 'Main nitrogen source',
    altNSource: 'Alternative N + S',
    phosphorusSource: 'Phosphorus',
    pPlusS: 'Phosphorus + sulfur',
    potassiumSource: 'Potassium',
    saferForTubers: 'Safer for tubers',
    organicMatter: 'Organic matter',
    phCorrection: 'pH correction + Mg',
    disclaimer: 'This report is generated by AI. Consult with agricultural experts for specific advice.',
    seedingMethod: 'Seeding Method',
    directSeeding: 'Direct seeding - no nursery stage',
    directPlanting: 'Planted directly using seed tubers',
    nurseryFert: 'Nursery Fertilizer',
    fieldFert: 'Field Fertilizer',
    pdfFilename: 'crop_fertilizer_recommendation'
  },
  sinhala: {
    title: 'බෝග පොහොර නිර්දේශ වාර්තාව',
    subtitle: 'ප්‍රශස්ත පොහොර අවශ්‍යතා',
    farmer: 'ගොවියා',
    date: 'දිනය',
    id: 'හැඳුනුම්පත් අංකය',
    soilInfo: 'පස සහ ස්ථාන තොරතුරු',
    soilType: 'පස වර්ගය',
    soilpH: 'පසේ pH අගය',
    nitrogen: 'නයිට්‍රජන්',
    phosphorus: 'පොස්පරස්',
    potassium: 'පොටෑසියම්',
    district: 'දිස්ත්‍රික්කය',
    agroZone: 'කෘෂි පාරිසරික කලාපය',
    season: 'කන්නය',
    landArea: 'ඉඩම් ප්‍රමාණය',
    hectares: 'හෙක්ටයාර',
    avgHumidity: 'සාමාන්‍ය ආර්ද්‍රතාවය',
    avgRainfall: 'සාමාන්‍ය වර්ෂාපතනය',
    temperature: 'උෂ්ණත්වය',
    weather: 'කාලගුණ තත්ත්වයන්',
    windSpeed: 'සුළඟේ වේගය',
    precipitation: 'වර්ෂාපතනය',
    cropRec: 'කෘත්‍රිම බුද්ධි බෝග නිර්දේශය',
    bestMatch: 'හොඳම ගැලපීම',
    confidence: 'විශ්වාසය',
    modelAccuracy: 'ආකෘති නිරවද්‍යතාව',
    altOptions: 'විකල්ප විකල්ප',
    fertilizerRec: 'පොහොර අවශ්‍යතා',
    purpose: 'අරමුණ',
    rate: 'හෙක්ටයාරයකට අනුපාතය',
    totalNeeded: 'ඔබේ ඉඩම සඳහා අවශ්‍ය මුළු ප්‍රමාණය',
    soilConsider: 'පස පිළිබඳ සැලකිලිමත් විය යුතු කරුණු',
    managementTips: 'කළමනාකරණ ඉඟි',
    basal: 'මූලික',
    topDressed: 'මතුපිට යෙදීම',
    or: 'හෝ',
    mainNSource: 'ප්‍රධාන නයිට්‍රජන් ප්‍රභවය',
    altNSource: 'විකල්ප N + S',
    phosphorusSource: 'පොස්පරස්',
    pPlusS: 'පොස්පරස් + සල්ෆර්',
    potassiumSource: 'පොටෑසියම්',
    saferForTubers: 'අල බෝග සඳහා ආරක්ෂිතයි',
    organicMatter: 'කාබනික ද්‍රව්‍ය',
    phCorrection: 'pH නිවැරදි කිරීම + Mg',
    disclaimer: 'මෙම වාර්තාව AI මගින් ජනනය කර ඇත. නිශ්චිත උපදෙස් සඳහා කෘෂිකාර්මික විශේෂඥයින් සමඟ සාකච්ඡා කරන්න.',
    seedingMethod: 'බීජ රෝපණ ක්‍රමය',
    directSeeding: 'සෘජු බීජ රෝපණය - තවාන් අවධියක් නැත',
    directPlanting: 'බීජ අල භාවිතයෙන් සෘජුවම රෝපණය කරන ලදී',
    nurseryFert: 'තවාන් පොහොර',
    fieldFert: 'ක්ෂේත්‍ර පොහොර',
    pdfFilename: 'boga_pohoora_nirdeshaya'
  },
  tamil: {
    title: 'பயிர் உர பரிந்துரை அறிக்கை',
    subtitle: 'உகந்த உர தேவைகள்',
    farmer: 'விவசாயி',
    date: 'தேதி',
    id: 'அடையாள எண்',
    soilInfo: 'மண் மற்றும் இருப்பிட தகவல்',
    soilType: 'மண் வகை',
    soilpH: 'மண் pH',
    nitrogen: 'நைட்ரஜன்',
    phosphorus: 'பாஸ்பரஸ்',
    potassium: 'பொட்டாசியம்',
    district: 'மாவட்டம்',
    agroZone: 'வேளாண் சூழலியல் மண்டலம்',
    season: 'பருவம்',
    landArea: 'நிலப்பரப்பு',
    hectares: 'ஹெக்டேர்',
    avgHumidity: 'சராசரி ஈரப்பதம்',
    avgRainfall: 'சராசரி மழைப்பொழிவு',
    temperature: 'வெப்பநிலை',
    weather: 'வானிலை நிலைமைகள்',
    windSpeed: 'காற்றின் வேகம்',
    precipitation: 'மழைப்பொழிவு',
    cropRec: 'செயற்கை நுண்ணறிவு பயிர் பரிந்துரை',
    bestMatch: 'சிறந்த பொருத்தம்',
    confidence: 'நம்பிக்கை',
    modelAccuracy: 'மாதிரி துல்லியம்',
    altOptions: 'மாற்று விருப்பங்கள்',
    fertilizerRec: 'உர தேவைகள்',
    purpose: 'நோக்கம்',
    rate: 'ஹெக்டேருக்கான விகிதம்',
    totalNeeded: 'உங்கள் நிலத்திற்கு தேவையான மொத்தம்',
    soilConsider: 'மண் பரிசீலனைகள்',
    managementTips: 'மேலாண்மை குறிப்புகள்',
    basal: 'அடிப்படை',
    topDressed: 'மேல் உரமிடல்',
    or: 'அல்லது',
    mainNSource: 'முக்கிய நைட்ரஜன் ஆதாரம்',
    altNSource: 'மாற்று N + S',
    phosphorusSource: 'பாஸ்பரஸ்',
    pPlusS: 'பாஸ்பரஸ் + சல்பர்',
    potassiumSource: 'பொட்டாசியம்',
    saferForTubers: 'கிழங்கு பயிர்களுக்கு பாதுகாப்பானது',
    organicMatter: 'கரிம பொருள்',
    phCorrection: 'pH திருத்தம் + Mg',
    disclaimer: 'இந்த அறிக்கை AI மூலம் உருவாக்கப்பட்டது. குறிப்பிட்ட ஆலோசனைக்கு வேளாண் நிபுணர்களை கலந்தாலோசிக்கவும்.',
    seedingMethod: 'விதை முறை',
    directSeeding: 'நேரடி விதைப்பு - நாற்றங்கால் நிலை இல்லை',
    directPlanting: 'விதை கிழங்குகளைப் பயன்படுத்தி நேரடியாக நடப்பட்டது',
    nurseryFert: 'நாற்றங்கால் உரம்',
    fieldFert: 'வயல் உரம்',
    pdfFilename: 'payir_ura_parinturai'
  }
};

// Crop fertilizer data from the document
const cropFertilizerData = {
  potato: {
    varieties: ['Granola', 'Desiree'],
    seedingMethod: 'directPlanting',
    fertilizers: [
      { type: 'Urea', rate: '225 kg (75 kg basal + 150 kg top dressed in 2 splits)', purpose: 'mainNSource' },
      { type: 'Ammonium Sulphate', rate: '480 kg (split, equivalent to 225 kg Urea)', purpose: 'altNSource' },
      { type: 'TSP (Triple Super Phosphate)', rate: '150 kg', purpose: 'phosphorusSource' },
      { type: 'SSP (Single Super Phosphate)', rate: '300 kg', purpose: 'pPlusS' },
      { type: 'MOP (Muriate of Potash)', rate: '150 kg (100 kg basal + 50 kg top dressed)', purpose: 'potassiumSource' },
      { type: 'SOP (Sulfate of Potash)', rate: '160--180 kg', purpose: 'saferForTubers' },
      { type: 'FYM / Compost', rate: '10--15 tons', purpose: 'organicMatter' },
      { type: 'Dolomite (if pH < 5.5)', rate: '1--2 tons', purpose: 'phCorrection' }
    ]
  },
  carrot: {
    varieties: ['New Kuroda', 'Chantenay'],
    seedingMethod: 'directSeeding',
    fertilizers: [
      { type: 'Urea', rate: '110 kg (55 kg basal + 55 kg top dressed)', purpose: 'nitrogen' },
      { type: 'Ammonium Sulphate', rate: '230--250 kg', purpose: 'altNSource' },
      { type: 'TSP', rate: '100 kg', purpose: 'phosphorusSource' },
      { type: 'SSP', rate: '200 kg', purpose: 'pPlusS' },
      { type: 'SOP (preferred)', rate: '75 kg', purpose: 'potassiumSource' },
      { type: 'MOP', rate: '75 kg', purpose: 'potassiumSource' },
      { type: 'Compost / FYM', rate: '15--20 tons', purpose: 'organicMatter' },
      { type: 'Dolomite (optional)', rate: '1--1.5 tons', purpose: 'phCorrection' }
    ]
  },
  maize: {
    varieties: ['Pacific 984', 'Arjun'],
    seedingMethod: 'directSeeding',
    fertilizers: [
      { type: 'Urea', rate: '150 kg (50 kg basal + 100 kg top dressed in 2 splits)', purpose: 'nitrogen' },
      { type: 'Ammonium Sulphate', rate: '300--320 kg', purpose: 'altNSource' },
      { type: 'TSP', rate: '100 kg', purpose: 'phosphorusSource' },
      { type: 'SSP', rate: '200 kg', purpose: 'pPlusS' },
      { type: 'MOP', rate: '100 kg (75 basal + 25 top)', purpose: 'potassiumSource' },
      { type: 'FYM / Compost', rate: '10--15 tons', purpose: 'organicMatter' },
      { type: 'Dolomite (if acidic soil)', rate: '1--2 tons', purpose: 'phCorrection' }
    ]
  },
  'big onion': {
    varieties: ['Hybrid 62', 'Bhima Shakti'],
    seedingMethod: 'nurseryTransplant',
    nurseryFertilizers: [
      { type: 'Ammonium Sulphate', rate: '2--3 g', purpose: 'nitrogen' },
      { type: 'TSP', rate: '4 g', purpose: 'phosphorusSource' },
      { type: 'MOP', rate: '2 g', purpose: 'potassiumSource' },
      { type: 'FYM / Compost', rate: '1--2 kg', purpose: 'organicMatter' }
    ],
    fertilizers: [
      { type: 'Urea', rate: '100 kg (50 basal + 50 top)', purpose: 'nitrogen' },
      { type: 'Ammonium Sulphate', rate: '210 kg', purpose: 'altNSource' },
      { type: 'TSP', rate: '100 kg', purpose: 'phosphorusSource' },
      { type: 'MOP', rate: '75 kg (50 + 25)', purpose: 'potassiumSource' },
      { type: 'FYM / Compost', rate: '20 tons', purpose: 'organicMatter' },
      { type: 'Dolomite', rate: '1--2 tons (if required)', purpose: 'phCorrection' }
    ]
  },
  'red onion': {
    varieties: ['Vethalan', 'LKRON 1'],
    seedingMethod: 'nurseryTransplant',
    nurseryFertilizers: [
      { type: 'Ammonium Sulphate', rate: '2 g', purpose: 'nitrogen' },
      { type: 'SSP', rate: '4 g', purpose: 'phosphorusSource' },
      { type: 'SOP', rate: '2 g', purpose: 'potassiumSource' },
      { type: 'FYM / Compost', rate: '1--2 kg', purpose: 'organicMatter' }
    ],
    fertilizers: [
      { type: 'Urea', rate: '125 kg (75 + 50)', purpose: 'nitrogen' },
      { type: 'Ammonium Sulphate', rate: '265--275 kg', purpose: 'altNSource' },
      { type: 'TSP', rate: '100 kg', purpose: 'phosphorusSource' },
      { type: 'MOP', rate: '75 kg (50 + 25)', purpose: 'potassiumSource' },
      { type: 'FYM / Compost', rate: '15 tons', purpose: 'organicMatter' },
      { type: 'Dolomite', rate: '1--2 tons', purpose: 'phCorrection' }
    ]
  },
  tomato: {
    varieties: ['Maheshi', 'Thilina'],
    seedingMethod: 'nurseryTransplant',
    nurseryFertilizers: [
      { type: 'Ammonium Sulphate', rate: '2--3 g', purpose: 'nitrogen' },
      { type: 'TSP', rate: '4 g', purpose: 'phosphorusSource' },
      { type: 'SOP (preferred)', rate: '2 g', purpose: 'potassiumSource' },
      { type: 'FYM / Compost', rate: '1--2 kg', purpose: 'organicMatter' }
    ],
    fertilizers: [
      { type: 'Urea', rate: '110 kg (55 + 55)', purpose: 'nitrogen' },
      { type: 'Ammonium Sulphate', rate: '230--250 kg', purpose: 'altNSource' },
      { type: 'TSP', rate: '100 kg', purpose: 'phosphorusSource' },
      { type: 'MOP / SOP', rate: '100 kg (75 + 25)', purpose: 'potassiumSource' },
      { type: 'FYM / Compost', rate: '10--15 tons', purpose: 'organicMatter' },
      { type: 'Dolomite', rate: '1--1.5 tons', purpose: 'phCorrection' }
    ]
  }
};

// Main PDF generation function with multilingual support
export const generateFertilizerPDF = (
  selectedCrop,
  inputData,
  predictions,
  selectedFarmer,
  selectedLanguage = 'english'
) => {
  // Set the language translations
  const lang = translations[selectedLanguage] || translations.english;

  // Initialize PDF with improved design
  const doc = new jsPDF();

  // Add a logo and header section with brand colors
  const brandColor = '#10B981'; // Green color from the app
  const textColor = '#374151';
  const subtitleColor = '#6B7280';

  // Header bar
  doc.setFillColor(brandColor);
  doc.rect(0, 0, 210, 30, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.text(lang.title, 105, 15, { align: 'center' });
  doc.setFontSize(14);
  doc.text(lang.subtitle, 105, 25, { align: 'center' });

  // Date
  const today = new Date().toLocaleDateString();

  // Farmer info
  let y = 40;
  doc.setTextColor(textColor);
  if (selectedFarmer) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`${lang.farmer}: ${selectedFarmer.name}`, 20, y);
    doc.text(`${lang.id}: ${selectedFarmer.id}`, 140, y);
    y += 8;
  }
  doc.setFontSize(12);
  doc.text(`${lang.date}: ${today}`, 20, y);
  y += 15;

  // Soil & Location Information
  doc.setFillColor(240, 240, 240);
  doc.rect(14, y, 182, 10, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(brandColor);
  doc.text(lang.soilInfo, 16, y + 7);
  y += 15;

  // Soil data columns
  doc.setTextColor(textColor);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  const SD = inputData;
  const displaySoilInfo = (label, value, yPos, xPos = 20) => {
    doc.setFont('helvetica', 'bold');
    doc.text(`${label}:`, xPos, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(`${value}`, xPos + 40, yPos);
    return yPos + 8;
  };

  // Left column
  let leftY = y;
  leftY = displaySoilInfo(lang.soilType, SD.soilType, leftY);
  leftY = displaySoilInfo(lang.soilpH, SD.pH, leftY);
  leftY = displaySoilInfo(lang.nitrogen, `${SD.nitrogen} ppm`, leftY);
  leftY = displaySoilInfo(lang.phosphorus, `${SD.phosphorus} ppm`, leftY);
  leftY = displaySoilInfo(lang.potassium, `${SD.potassium} ppm`, leftY);

  // Right column
  let rightY = y;
  rightY = displaySoilInfo(lang.district, SD.district || '-', rightY, 120);
  rightY = displaySoilInfo(lang.agroZone, SD.agroZone || '-', rightY, 120);
  rightY = displaySoilInfo(lang.season, SD.season, rightY, 120);
  rightY = displaySoilInfo(lang.landArea, `${SD.landArea || 0} ${lang.hectares}`, rightY, 120);

  y = Math.max(leftY, rightY) + 5;

  // Crop Recommendation
  doc.setFillColor(240, 240, 240);
  doc.rect(14, y, 182, 10, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(brandColor);
  doc.text(lang.cropRec, 16, y + 7);
  y += 15;

  doc.setTextColor(textColor);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`${lang.bestMatch}: ${predictions.mlResult.predicted_crop}`, 20, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`${lang.confidence}: ${predictions.mlResult.confidence}%`, 20, y);
  y += 8;

  // Match crop data
  const cropName = predictions.mlResult.predicted_crop.toLowerCase();
  let matchedCrop = null;
  for (const [crop, data] of Object.entries(cropFertilizerData)) {
    if (cropName.includes(crop)) {
      matchedCrop = { name: crop, ...data };
      break;
    }
  }
  if (!matchedCrop) {
    matchedCrop = { name: 'general', ...cropFertilizerData.tomato };
  }

  // Fertilizer Requirements title
  y += 5;
  doc.setFillColor(240, 240, 240);
  doc.rect(14, y, 182, 10, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(brandColor);
  doc.text(`${lang.fertilizerRec} - ${predictions.mlResult.predicted_crop}`, 16, y + 7);
  y += 15;

  // Seeding method
  doc.setTextColor(textColor);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(`${lang.seedingMethod}: ${lang[matchedCrop.seedingMethod]}`, 20, y);
  y += 10;

  // Nursery fertilizer (if any)
  if (matchedCrop.nurseryFertilizers) {
    doc.setFontSize(12);
    doc.setTextColor(brandColor);
    doc.text(lang.nurseryFert, 20, y);
    y += 8;

    autoTable(doc, {
      startY: y,
      head: [[lang.fertilizerRec, lang.rate, lang.purpose]],
      body: matchedCrop.nurseryFertilizers.map(fert => [
        fert.type,
        fert.rate,
        lang[fert.purpose] || fert.purpose
      ]),
      headStyles: { fillColor: [16, 185, 129], textColor: [255, 255, 255] },
      alternateRowStyles: { fillColor: [240, 240, 240] },
      margin: { left: 20, right: 20 },
      styles: { fontSize: 10 }
    });

    y = doc.lastAutoTable.finalY + 10;
  }

  // Field fertilizer
  doc.setFontSize(12);
  doc.setTextColor(brandColor);
  doc.text(lang.fieldFert, 20, y);
  y += 8;

  // Total amounts by land area
  const landArea = parseFloat(SD.landArea) || 1;

  const bodyData = matchedCrop.fertilizers.map(fert => {
    let totalNeeded = '';
    const rangeMatch = fert.rate.match(/(\d+)(?:\-\-|\-)(\d+)/);
    if (rangeMatch) {
      const min = parseFloat(rangeMatch[1]) * landArea;
      const max = parseFloat(rangeMatch[2]) * landArea;
      totalNeeded = `${min.toFixed(1)} - ${max.toFixed(1)} ${fert.rate.includes('tons') ? 'tons' : 'kg'}`;
    } else {
      const singleMatch = fert.rate.match(/(\d+)\s*kg/);
      if (singleMatch) {
        const amount = parseFloat(singleMatch[1]) * landArea;
        totalNeeded = `${amount.toFixed(1)} kg`;
      }
    }
    return [fert.type, fert.rate, lang[fert.purpose] || fert.purpose, totalNeeded];
  });

  autoTable(doc, {
    startY: y,
    head: [[lang.fertilizerRec, lang.rate, lang.purpose, lang.totalNeeded]],
    body: bodyData,
    headStyles: { fillColor: [16, 185, 129], textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [240, 240, 240] },
    margin: { left: 20, right: 20 },
    styles: { fontSize: 10 }
  });

  y = doc.lastAutoTable.finalY + 10;

  if (y > 260) {
    doc.addPage();
    y = 20;
  }

  // Management Tips
  if (predictions.managementTips && predictions.managementTips.length > 0) {
    doc.setFillColor(240, 240, 240);
    doc.rect(14, y, 182, 10, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(brandColor);
    doc.text(lang.managementTips, 16, y + 7);
    y += 15;

    doc.setTextColor(textColor);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    predictions.managementTips.forEach(tip => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      doc.circle(20, y - 2, 1, 'F');
      doc.text(tip, 25, y);
      y += 8;
    });

    y += 5;
  }

  // Soil Considerations
  if (predictions.soilIssues && predictions.soilIssues.length > 0) {
    if (y > 250) {
      doc.addPage();
      y = 20;
    }

    doc.setFillColor(240, 240, 240);
    doc.rect(14, y, 182, 10, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(brandColor);
    doc.text(lang.soilConsider, 16, y + 7);
    y += 15;

    doc.setTextColor(textColor);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    predictions.soilIssues.forEach(issue => {
      doc.circle(20, y - 2, 1, 'F');
      doc.text(issue, 25, y);
      y += 8;
    });

    y += 5;
  }

  // Footer (disclaimer + page numbers)
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(subtitleColor);
    doc.text(lang.disclaimer, 105, 285, { align: 'center' });
    doc.text(`${i} / ${pageCount}`, 190, 285, { align: 'right' });
    doc.setFillColor(brandColor);
    doc.circle(15, 285, 3, 'F');
  }

  // Filename
  const dateStr = new Date().toISOString().slice(0, 10).replace(/-/g, '');
  const filename = `${lang.pdfFilename}_${cropName}_${dateStr}.pdf`;

  return {
    doc,
    filename,
    save: () => doc.save(filename)
  };
};
