'use client';

import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

/* ----------------------- helpers / constants ----------------------------- */
const translations = {
  english: {
    title: 'Crop Fertilizer Recommendation Report',
    subtitle: 'Optimized Fertilizer Requirements',
    farmer: 'Farmer',
    date: 'Date',
    id: 'ID',
    soilInfo: 'Soil & Location Information',
    soilType: 'Soil Type',
    soilpH: 'Soil pH',
    nitrogen: 'Nitrogen',
    phosphorus: 'Phosphorus',
    potassium: 'Potassium',
    district: 'District',
    agroZone: 'Agro-ecological Zone',
    season: 'Season',
    landArea: 'Land Area',
    hectares: 'hectares',
    cropRec: 'AI Crop Recommendation',
    bestMatch: 'Best Match',
    confidence: 'Confidence',
    fertilizerRec: 'Fertilizer Requirements',
    purpose: 'Purpose',
    rate: 'Rate per hectare',
    totalNeeded: 'Total needed for your land',
    soilConsider: 'Soil Considerations',
    managementTips: 'Management Tips',
    seedingMethod: 'Seeding Method',
    directSeeding: 'Direct seeding - no nursery stage',
    directPlanting: 'Planted directly using seed tubers',
    nurseryFert: 'Nursery Fertilizer',
    fieldFert: 'Field Fertilizer',
    pdfFilename: 'crop_fertilizer_recommendation',
    disclaimer:
      'This report is generated by AI. Consult agricultural experts for field-specific advice.',
  },
  sinhala: {
    title: 'බෝග පොහොර නිර්දේශ වාර්තාව',
    subtitle: 'ප්‍රශස්ත පොහොර අවශ්‍යතා',
    farmer: 'ගොවියා',
    date: 'දිනය',
    id: 'හැඳුනුම්පත් අංකය',
    soilInfo: 'පස සහ ස්ථාන තොරතුරු',
    soilType: 'පස වර්ගය',
    soilpH: 'පසේ pH අගය',
    nitrogen: 'නයිට්‍රජන්',
    phosphorus: 'පොස්පරස්',
    potassium: 'පොටෑසියම්',
    district: 'දිස්ත්‍රික්කය',
    agroZone: 'කෘෂි පාරිසරික කලාපය',
    season: 'කන්නය',
    landArea: 'ඉඩම් ප්‍රමාණය',
    hectares: 'හෙක්ටයාර',
    cropRec: 'කෘත්‍රිම බුද්ධි බෝග නිර්දේශය',
    bestMatch: 'හොඳම ගැලපීම',
    confidence: 'විශ්වාසය',
    fertilizerRec: 'පොහොර අවශ්‍යතා',
    purpose: 'අරමුණ',
    rate: 'හෙක්ටයාරයකට අනුපාතය',
    totalNeeded: 'ඔබේ ඉඩම සඳහා අවශ්‍ය මුළු ප්‍රමාණය',
    soilConsider: 'පස පිළිබඳ සැලකිලිමත් කරුණු',
    managementTips: 'කළමනාකරණ ඉඟි',
    seedingMethod: 'බීජ රෝපණ ක්‍රමය',
    directSeeding: 'සෘජු බීජ රෝපණය - තවාන් අවධියක් නැත',
    directPlanting: 'බීජ අල භාවිතයෙන් සෘජුවම රෝපණය',
    nurseryFert: 'තවාන් පොහොර',
    fieldFert: 'ක්ෂේත්‍ර පොහොර',
    pdfFilename: 'boga_pohoora_nirdeshaya',
    disclaimer:
      'මෙම වාර්තාව AI මගින් ජනනය කර ඇත. ක්ෂේත්‍ර විශේෂ උපදෙස් සඳහා විශේෂඥයකුගේ උපදෙස් ලබා ගන්න.',
  },
  tamil: {
    title: 'பயிர் உர பரிந்துரை அறிக்கை',
    subtitle: 'உகந்த உர தேவைகள்',
    farmer: 'விவசாயி',
    date: 'தேதி',
    id: 'அடையாள எண்',
    soilInfo: 'மண் & இருப்பிடத் தகவல்',
    soilType: 'மண் வகை',
    soilpH: 'மண் pH',
    nitrogen: 'நைட்ரஜன்',
    phosphorus: 'பாஸ்பரஸ்',
    potassium: 'பொட்டாசியம்',
    district: 'மாவட்டம்',
    agroZone: 'வேளாண் சூழலியல் மண்டலம்',
    season: 'பருவம்',
    landArea: 'நிலப்பரப்பு',
    hectares: 'ஹெக்டேர்',
    cropRec: 'AI பயிர் பரிந்துரை',
    bestMatch: 'சிறந்த பொருத்தம்',
    confidence: 'நம்பிக்கை',
    fertilizerRec: 'உர தேவைகள்',
    purpose: 'நோக்கம்',
    rate: 'ஹெக்டேருக்கான விகிதம்',
    totalNeeded: 'உங்கள் நிலத்திற்கு தேவையான மொத்தம்',
    soilConsider: 'மண் பரிசீலனைகள்',
    managementTips: 'மேலாண்மை குறிப்புகள்',
    seedingMethod: 'விதை முறை',
    directSeeding: 'நேரடி விதைப்பு - நாற்றங்கால் இல்லை',
    directPlanting: 'விதை கிழங்குகளால் நேரடி நடவு',
    nurseryFert: 'நாற்றங்கால் உரம்',
    fieldFert: 'வயல் உரம்',
    pdfFilename: 'payir_ura_parinturai',
    disclaimer:
      'இந்த அறிக்கை AI மூலம் உருவாக்கப்பட்டுள்ளது. களத்திற்கான விவர ஆலோசனைகளுக்கு நிபுணர்களை அணுகவும்.',
  },
};

const cropFertilizerData = {
  tomato: {
    seedingMethod: 'nurseryTransplant',
    nurseryFertilizers: [
      { type: 'Ammonium Sulphate', rate: '2–3 kg', purpose: 'Nitrogen' },
      { type: 'TSP', rate: '4 kg', purpose: 'Phosphorus' },
      { type: 'SOP (preferred)', rate: '2 kg', purpose: 'Potassium' },
      { type: 'FYM / Compost', rate: '1–2 kg', purpose: 'Better rooting, structure' },
    ],
    fertilizers: [
      { type: 'Urea', rate: '110 kg (55 + 55)', purpose: 'Nitrogen' },
      { type: 'Ammonium Sulphate', rate: '230–250 kg', purpose: 'For sulfur-deficient soils' },
      { type: 'TSP', rate: '100 kg', purpose: 'Strong root establishment' },
      { type: 'MOP / SOP', rate: '100 kg (75 + 25)', purpose: 'SOP improves fruit taste' },
      { type: 'FYM / Compost', rate: '10–15 tons', purpose: 'Nutrient buffering' },
      { type: 'Dolomite', rate: '1–1.5 tons', purpose: 'Neutralize acidity' },
    ],
  },
  potato: {
    seedingMethod: 'directPlanting',
    nurseryFertilizers: null,
    fertilizers: [
      { type: 'Urea', rate: '225 kg (75 kg basal + 150 kg top dressed in 2 splits)', purpose: 'Main nitrogen source' },
      { type: 'Ammonium Sulphate', rate: '480 kg (split, equivalent to 225 kg Urea)', purpose: 'Alternative N + S' },
      { type: 'TSP (Triple Super Phosphate)', rate: '150 kg', purpose: 'Phosphorus' },
      { type: 'SSP (Single Super Phosphate)', rate: '300 kg', purpose: 'Phosphorus + sulfur' },
      { type: 'MOP (Muriate of Potash)', rate: '150 kg (100 kg basal + 50 kg top dressed)', purpose: 'Potassium' },
      { type: 'SOP (Sulfate of Potash)', rate: '160–180 kg', purpose: 'Safer for tubers' },
      { type: 'FYM / Compost', rate: '10–15 tons', purpose: 'Organic matter' },
      { type: 'Dolomite (if pH < 5.5)', rate: '1–2 tons', purpose: 'pH correction + Mg' },
    ],
  },
  carrot: {
    seedingMethod: 'directSeeding',
    nurseryFertilizers: null,
    fertilizers: [
      { type: 'Urea', rate: '110 kg (55 kg basal + 55 kg top dressed)', purpose: 'Nitrogen' },
      { type: 'Ammonium Sulphate', rate: '230–250 kg', purpose: 'Alternative to Urea' },
      { type: 'TSP', rate: '100 kg', purpose: 'Phosphorus' },
      { type: 'SSP', rate: '200 kg', purpose: 'Alternative P' },
      { type: 'SOP (preferred)', rate: '75 kg', purpose: 'Potassium' },
      { type: 'MOP', rate: '75 kg', purpose: 'Only if soil allows' },
      { type: 'Compost / FYM', rate: '15–20 tons', purpose: 'Organic matter' },
      { type: 'Dolomite (optional)', rate: '1–1.5 tons', purpose: 'For pH and Mg' },
    ],
  },
  maize: {
    seedingMethod: 'directSeeding',
    nurseryFertilizers: null,
    fertilizers: [
      { type: 'Urea', rate: '150 kg (50 kg basal + 100 kg top dressed in 2 splits)', purpose: 'Nitrogen' },
      { type: 'Ammonium Sulphate', rate: '300–320 kg', purpose: 'Alternate N & S source' },
      { type: 'TSP', rate: '100 kg', purpose: 'Basal phosphorus' },
      { type: 'SSP', rate: '200 kg', purpose: 'Lower P but adds sulfur' },
      { type: 'MOP', rate: '100 kg (75 basal + 25 top)', purpose: 'Potassium' },
      { type: 'FYM / Compost', rate: '10–15 tons', purpose: 'Improves water retention' },
      { type: 'Dolomite (if acidic soil)', rate: '1–2 tons', purpose: 'pH correction' },
    ],
  },
  'big onion': {
    seedingMethod: 'nurseryTransplant',
    nurseryFertilizers: [
      { type: 'Ammonium Sulphate', rate: '2–3 kg', purpose: 'Light N + S source' },
      { type: 'TSP', rate: '4 kg', purpose: 'Phosphorus' },
      { type: 'MOP', rate: '2 kg', purpose: 'Potassium' },
      { type: 'FYM / Compost', rate: '1–2 kg', purpose: 'Soil texture, nutrients' },
    ],
    fertilizers: [
      { type: 'Urea', rate: '100 kg (50 basal + 50 top)', purpose: 'Nitrogen' },
      { type: 'Ammonium Sulphate', rate: '210 kg', purpose: 'Alternative N & S' },
      { type: 'TSP', rate: '100 kg', purpose: 'Phosphorus' },
      { type: 'MOP', rate: '75 kg (50 + 25)', purpose: 'Potassium' },
      { type: 'FYM / Compost', rate: '20 tons', purpose: 'Organic matter' },
      { type: 'Dolomite', rate: '1–2 tons', purpose: 'pH & Mg correction' },
    ],
  },
  'red onion': {
    seedingMethod: 'nurseryTransplant',
    nurseryFertilizers: [
      { type: 'Ammonium Sulphate', rate: '2 kg', purpose: 'Nitrogen & sulfur' },
      { type: 'SSP', rate: '4 kg', purpose: 'Phosphorus' },
      { type: 'SOP', rate: '2 kg', purpose: 'Potassium' },
      { type: 'FYM / Compost', rate: '1–2 kg', purpose: 'Organic matter' },
    ],
    fertilizers: [
      { type: 'Urea', rate: '125 kg (75 + 50)', purpose: 'Nitrogen' },
      { type: 'Ammonium Sulphate', rate: '265–275 kg', purpose: 'Alt. for nitrogen' },
      { type: 'TSP', rate: '100 kg', purpose: 'Basal phosphorus' },
      { type: 'MOP', rate: '75 kg (50 + 25)', purpose: 'Potassium' },
      { type: 'FYM / Compost', rate: '15 tons', purpose: 'Organic support' },
      { type: 'Dolomite', rate: '1–2 tons', purpose: 'pH correction' },
    ],
  },
};

const dashRegex = /[\u2012\u2013\u2014-]/; // any dash: –, —, -

function totalForLand(rateText = '', landArea = 1) {
  const range = rateText.match(new RegExp(`(\\d+)\\s*${dashRegex.source}\\s*(\\d+)\\s*(tons|kg|g)`, 'i'));
  if (range) return `${(+range[1] * landArea).toFixed(1)} - ${(+range[2] * landArea).toFixed(1)} ${range[3]}`;
  const single = rateText.match(/(\d+)\s*(tons|kg|g)/i);
  if (single) return `${(+single[1] * landArea).toFixed(1)} ${single[2]}`;
  return '';
}

export async function generateFertilizerPDF(
  selectedCrop,
  inputData,
  predictions,
  selectedFarmer,
  selectedLanguage = 'english'
) {
  const lang = translations[selectedLanguage] || translations.english;
  const landArea = parseFloat(inputData?.landArea) || 1;
  const predictedCrop = predictions?.mlResult?.predicted_crop || selectedCrop || 'Crop';
  const matchedCropData = Object.entries(cropFertilizerData).find(([k]) =>
    String(predictedCrop).toLowerCase().includes(k)
  )?.[1] || cropFertilizerData.tomato;

  // 1. Create a hidden HTML element to render the content
  const htmlContent = `
    <div id="pdf-content" style="width: 210mm; font-family: 'Noto Sans Sinhala', 'Noto Serif Sinhala', sans-serif; padding: 10mm; box-sizing: border-box; color: rgb(55, 65, 81);">
      <style>
        @media print {
          body * {
            visibility: hidden;
          }
          #pdf-content, #pdf-content * {
            visibility: visible;
          }
          #pdf-content {
            position: absolute;
            left: 0;
            top: 0;
          }
        }
        .header { background-color: rgb(16, 185, 129); color: white; padding: 20px; text-align: center; }
        .section-header { background-color: rgb(242, 242, 242); padding: 5px 10px; color: rgb(16, 185, 129); font-weight: bold; }
        .grid-container { display: grid; grid-template-columns: repeat(2, 1fr); gap: 10px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 10px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: rgb(16, 185, 129); color: white; }
        .list-item { display: flex; align-items: center; margin-bottom: 5px; }
        .list-dot { width: 4px; height: 4px; background-color: rgb(55, 65, 81); border-radius: 50%; margin-right: 10px; }
        h1, h4 { margin: 0; }
        p { margin: 0; }
        .footer {
          position: fixed;
          bottom: 10mm;
          left: 10mm;
          right: 10mm;
          text-align: center;
          font-size: 9px;
          color: rgb(107, 114, 128);
        }
      </style>
      
      <div class="header">
        <h1 style="font-size: 20px; font-weight: bold;">${lang.title}</h1>
        <p style="font-size: 12px;">${lang.subtitle}</p>
      </div>

      <div style="margin-top: 20px; font-size: 11px;">
        ${selectedFarmer?.name ? `<p>${lang.farmer}: ${selectedFarmer.name} ${selectedFarmer.id ? `(${lang.id}: ${selectedFarmer.id})` : ''}</p>` : ''}
        <p style="margin-top: 5px;">${lang.date}: ${new Date().toLocaleDateString()}</p>
      </div>

      <div style="margin-top: 15px;">
        <div class="section-header">${lang.soilInfo}</div>
        <div class="grid-container" style="margin-top: 10px;">
          <div>
            <p>${lang.soilType}: ${inputData?.soilType ?? '-'}</p>
            <p style="margin-top: 5px;">${lang.soilpH}: ${inputData?.pH ?? '-'}</p>
            <p style="margin-top: 5px;">${lang.nitrogen}: ${inputData?.nitrogen != null ? `${inputData.nitrogen} ppm` : '-'}</p>
            <p style="margin-top: 5px;">${lang.phosphorus}: ${inputData?.phosphorus != null ? `${inputData.phosphorus} ppm` : '-'}</p>
            <p style="margin-top: 5px;">${lang.potassium}: ${inputData?.potassium != null ? `${inputData.potassium} ppm` : '-'}</p>
          </div>
          <div>
            <p>${lang.district}: ${inputData?.district ?? '-'}</p>
            <p style="margin-top: 5px;">${lang.agroZone}: ${inputData?.agroZone ?? '-'}</p>
            <p style="margin-top: 5px;">${lang.season}: ${inputData?.season ?? '-'}</p>
            <p style="margin-top: 5px;">${lang.landArea}: ${inputData?.landArea || 1} ${lang.hectares}</p>
          </div>
        </div>
      </div>
      
      <div style="margin-top: 15px;">
        <div class="section-header">${lang.cropRec}</div>
        <p style="font-weight: bold; font-size: 12px; margin-top: 10px;">${lang.bestMatch}: ${predictedCrop}</p>
        ${predictions?.mlResult?.confidence != null ? `<p style="font-size: 10px; margin-top: 5px;">${lang.confidence}: ${predictions.mlResult.confidence}%</p>` : ''}
      </div>

      <div style="margin-top: 15px;">
        <div class="section-header">${lang.fertilizerRec} - ${predictedCrop}</div>
        <p style="font-weight: bold; font-size: 11px; margin-top: 10px;">${lang.seedingMethod}: ${translations[selectedLanguage]?.[matchedCropData.seedingMethod] || matchedCropData.seedingMethod}</p>

        ${matchedCropData.nurseryFertilizers?.length ? `
          <h4 style="margin-top: 15px;">${lang.nurseryFert}</h4>
          <table cellspacing="0" cellpadding="0">
            <thead>
              <tr>
                <th>Fertilizer Type</th>
                <th>${lang.rate}</th>
                <th>${lang.purpose}</th>
              </tr>
            </thead>
            <tbody>
              ${matchedCropData.nurseryFertilizers.map(f => `
                <tr>
                  <td>${f.type}</td>
                  <td>${f.rate}</td>
                  <td>${f.purpose}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        ` : ''}

        <h4 style="margin-top: 15px;">${lang.fieldFert}</h4>
        <table cellspacing="0" cellpadding="0">
          <thead>
            <tr>
              <th>Fertilizer Type</th>
              <th>${lang.rate}</th>
              <th>${lang.purpose}</th>
              <th>${lang.totalNeeded}</th>
            </tr>
          </thead>
          <tbody>
            ${(matchedCropData.fertilizers || []).map(f => `
              <tr>
                <td>${f.type}</td>
                <td>${f.rate}</td>
                <td>${f.purpose}</td>
                <td>${totalForLand(f.rate, landArea)}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </div>

      ${predictions?.managementTips?.length ? `
        <div style="margin-top: 15px;">
          <div class="section-header">${lang.managementTips}</div>
          <div style="margin-top: 10px;">
            ${predictions.managementTips.map(tip => `
              <div class="list-item">
                <span class="list-dot"></span>
                <span style="font-size: 10px;">${tip}</span>
              </div>
            `).join('')}
          </div>
        </div>
      ` : ''}

      ${predictions?.soilIssues?.length ? `
        <div style="margin-top: 15px;">
          <div class="section-header">${lang.soilConsider}</div>
          <div style="margin-top: 10px;">
            ${predictions.soilIssues.map(issue => `
              <div class="list-item">
                <span class="list-dot"></span>
                <span style="font-size: 10px;">${issue}</span>
              </div>
            `).join('')}
          </div>
        </div>
      ` : ''}

      <div style="text-align: center; margin-top: 20px; font-size: 9px; color: rgb(107, 114, 128);">
        <p>${lang.disclaimer}</p>
      </div>
    </div>
  `;

  // 2. Add the content to a temporary div in the document body
  const tempDiv = document.createElement('div');
  tempDiv.innerHTML = htmlContent;
  tempDiv.style.position = 'absolute';
  tempDiv.style.left = '-9999px';
  document.body.appendChild(tempDiv);

  // 3. Generate the PDF from the HTML content
  const canvas = await html2canvas(tempDiv, { scale: 2 });
  const imgData = canvas.toDataURL('image/png');
  const imgProps = {
    width: 210, // A4 width in mm
    height: (canvas.height * 210) / canvas.width,
  };

  const doc = new jsPDF('p', 'mm', 'a4');
  doc.addImage(imgData, 'PNG', 0, 0, imgProps.width, imgProps.height);

  // 4. Clean up the temporary div
  document.body.removeChild(tempDiv);

  const dateStr = new Date().toISOString().slice(0, 10);
  const safeCrop = String(predictedCrop)
    .trim()
    .toLowerCase()
    .replace(/\s+/g, '_');
  const filename = `${lang.pdfFilename}_${safeCrop}_${dateStr}.pdf`;

  return { doc, filename, save: () => doc.save(filename) };
}